In [4]:
import cvxpy
import numpy as np
import matplotlib.pylab as plt
import pandas as pd
import cvxpy as cp

## A complete code

In [5]:
R = cp.Variable((9,9),boolean=True)
S = cp.Variable((9,9),boolean=True)
T = cp.Variable((9,9),boolean=True)
U = cp.Variable((9,9),boolean=True)
V = cp.Variable((9,9),boolean=True)
W = cp.Variable((9,9),boolean=True)
X= cp.Variable((9,9),boolean=True)
Y= cp.Variable((9,9),boolean=True)
Z= cp.Variable((9,9),boolean=True)

constraints = [
                cp.sum(R, axis=0, keepdims=True) == 1, cp.sum(R, axis=1, keepdims=True) == 1,
                   cp.sum(R[0:3,0:3]) == 1, cp.sum(R[0:3,3:6]) == 1, cp.sum(R[0:3,6:9]) == 1,
                   cp.sum(R[3:6,0:3]) == 1, cp.sum(R[3:6,3:6]) == 1, cp.sum(R[3:6,6:9]) == 1,
                   cp.sum(R[6:9,0:3]) == 1, cp.sum(R[6:9,3:6]) == 1, cp.sum(R[6:9,6:9]) == 1,
               cp.sum(S, axis=0, keepdims=True) == 1, cp.sum(S, axis=1, keepdims=True) == 1,
                   cp.sum(S[0:3,0:3]) == 1, cp.sum(S[0:3,3:6]) == 1, cp.sum(S[0:3,6:9]) == 1,
                   cp.sum(S[3:6,0:3]) == 1, cp.sum(S[3:6,3:6]) == 1, cp.sum(S[3:6,6:9]) == 1,
                   cp.sum(S[6:9,0:3]) == 1, cp.sum(S[6:9,3:6]) == 1, cp.sum(S[6:9,6:9]) == 1,
               cp.sum(T, axis=0, keepdims=True) == 1, cp.sum(T, axis=1, keepdims=True) == 1,
                   cp.sum(T[0:3,0:3]) == 1, cp.sum(T[0:3,3:6]) == 1, cp.sum(T[0:3,6:9]) == 1,
                   cp.sum(T[3:6,0:3]) == 1, cp.sum(T[3:6,3:6]) == 1, cp.sum(T[3:6,6:9]) == 1,
                   cp.sum(T[6:9,0:3]) == 1, cp.sum(T[6:9,3:6]) == 1, cp.sum(T[6:9,6:9]) == 1,
               cp.sum(U, axis=0, keepdims=True) == 1, cp.sum(U, axis=1, keepdims=True) == 1,
                   cp.sum(U[0:3,0:3]) == 1, cp.sum(U[0:3,3:6]) == 1, cp.sum(U[0:3,6:9]) == 1,
                   cp.sum(U[3:6,0:3]) == 1, cp.sum(U[3:6,3:6]) == 1, cp.sum(U[3:6,6:9]) == 1,
                   cp.sum(U[6:9,0:3]) == 1, cp.sum(U[6:9,3:6]) == 1, cp.sum(U[6:9,6:9]) == 1,
               cp.sum(V, axis=0, keepdims=True) == 1, cp.sum(V, axis=1, keepdims=True) == 1,
                   cp.sum(V[0:3,0:3]) == 1, cp.sum(V[0:3,3:6]) == 1, cp.sum(V[0:3,6:9]) == 1,
                   cp.sum(V[3:6,0:3]) == 1, cp.sum(V[3:6,3:6]) == 1, cp.sum(V[3:6,6:9]) == 1,
                   cp.sum(V[6:9,0:3]) == 1, cp.sum(V[6:9,3:6]) == 1, cp.sum(V[6:9,6:9]) == 1,
               cp.sum(W, axis=0, keepdims=True) == 1, cp.sum(W, axis=1, keepdims=True) == 1,
                   cp.sum(W[0:3,0:3]) == 1, cp.sum(W[0:3,3:6]) == 1, cp.sum(W[0:3,6:9]) == 1,
                   cp.sum(W[3:6,0:3]) == 1, cp.sum(W[3:6,3:6]) == 1, cp.sum(W[3:6,6:9]) == 1,
                   cp.sum(W[6:9,0:3]) == 1, cp.sum(W[6:9,3:6]) == 1, cp.sum(W[6:9,6:9]) == 1,
               cp.sum(X, axis=0, keepdims=True) == 1, cp.sum(X, axis=1, keepdims=True) == 1,
                   cp.sum(X[0:3,0:3]) == 1, cp.sum(X[0:3,3:6]) == 1, cp.sum(X[0:3,6:9]) == 1,
                   cp.sum(X[3:6,0:3]) == 1, cp.sum(X[3:6,3:6]) == 1, cp.sum(X[3:6,6:9]) == 1,
                   cp.sum(X[6:9,0:3]) == 1, cp.sum(X[6:9,3:6]) == 1, cp.sum(X[6:9,6:9]) == 1,
               cp.sum(Y, axis=0, keepdims=True) == 1, cp.sum(Y, axis=1, keepdims=True) == 1,
                   cp.sum(Y[0:3,0:3]) == 1, cp.sum(Y[0:3,3:6]) == 1, cp.sum(Y[0:3,6:9]) == 1,
                   cp.sum(Y[3:6,0:3]) == 1, cp.sum(Y[3:6,3:6]) == 1, cp.sum(Y[3:6,6:9]) == 1,
                   cp.sum(Y[6:9,0:3]) == 1, cp.sum(Y[6:9,3:6]) == 1, cp.sum(Y[6:9,6:9]) == 1,
               cp.sum(Z, axis=0, keepdims=True) == 1, cp.sum(Z, axis=1, keepdims=True) == 1,
                   cp.sum(Z[0:3,0:3]) == 1, cp.sum(Z[0:3,3:6]) == 1, cp.sum(Z[0:3,6:9]) == 1,
                   cp.sum(Z[3:6,0:3]) == 1, cp.sum(Z[3:6,3:6]) == 1, cp.sum(Z[3:6,6:9]) == 1,
                   cp.sum(Z[6:9,0:3]) == 1, cp.sum(Z[6:9,3:6]) == 1, cp.sum(Z[6:9,6:9]) == 1
                ]

for i in range(0,9):
    for j in range(0,9):
        constraints += [R[i,j] + S[i,j] + T[i,j] + U[i,j] + V[i,j] + W[i,j] + X[i,j] + Y[i,j] + Z[i,j] == 1]

obj = cp.Minimize(cp.sum(cp.sum(R) + cp.sum(S) + cp.sum(T) + cp.sum(U) + cp.sum(V) + cp.sum(W) + cp.sum(X) + cp.sum(Y) + cp.sum(Z)))
# obj = cp.Minimize(cp.sum(Z))

In [7]:
# Form and solve problem.
prob = cp.Problem(obj, constraints)
prob.solve # Returns the optimal value.
print("status:", prob.status)
print("optimal value", prob.value)
print("final solution", (R.value + S.value*2 + T.value*3 + U.value*4 + V.value*5 + W.value*6 + X.value*7 + Y.value*8 + Z.value*9))

status: None
optimal value None


TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

 ## A non-complete code

In [45]:
from cvxpy import *
import numpy as np

x = Variable((9, 9), integer=True)
obj = Minimize(sum(x)) #whatever, if the constrains are fulfilled it will be fine
const = [x >= 1, #all values should be >= 1
         x <= 9, #all values should be <= 9
         sum(x, axis=0) == 45,  # sum of all rows should be 45
         sum(x, axis=1) == 45,  # sum of all cols should be 45
         sum(x[0:3, 0:3]) == 45, sum(x[0:3, 3:6]) == 45, #sum of all squares should be 45
         sum(x[0:3, 6:9]) == 45,
         sum(x[3:6, 0:3]) == 45, sum(x[3:6, 3:6]) == 45,
         sum(x[3:6, 6:9]) == 45,
         sum(x[6:9, 0:3]) == 45, sum(x[6:9, 3:6]) == 45,
         sum(x[6:9, 6:9]) == 45,
         x[0, 7] == 7, #the values themselves
         x[0, 8] == 1,
         x[1, 1] == 6,
         x[1, 4] == 3,
         x[2, 4] == 2,
         x[3, 0] == 7,
         x[3, 4] == 6,
         x[3, 6] == 3,
         x[4, 0] == 4,
         x[4, 6] == 2,
         x[5, 0] == 1,
         x[5, 3] == 4,
         x[6, 3] == 7,
         x[6, 5] == 5,
         x[6, 7] == 8,
         x[7, 1] == 2,
         x[8, 3] == 1]

prob = Problem(objective=obj, constraints=const)
# prob.solve(solver=cvxpy.GLPK_MI)

405.0

In [46]:
print("status:", prob.status)
print("optimal value", prob.value)
print("optimal var", x.value)

status: optimal
optimal value 405.0
optimal var [[9. 7. 1. 1. 9. 2. 8. 7. 1.]
 [9. 6. 2. 9. 3. 5. 9. 1. 1.]
 [1. 1. 9. 5. 2. 9. 4. 9. 5.]
 [7. 9. 1. 8. 6. 1. 3. 1. 9.]
 [4. 9. 4. 1. 9. 4. 2. 6. 6.]
 [1. 1. 9. 4. 3. 9. 8. 1. 9.]
 [1. 1. 9. 7. 1. 5. 9. 8. 4.]
 [4. 2. 9. 9. 7. 1. 1. 3. 9.]
 [9. 9. 1. 1. 5. 9. 1. 9. 1.]]
